### ISSUE TITLE
Disconnection issues

### ISSUE THREAD

**Issue by csmith** [ShaneMcC/DFBnc#98]
DFBnc 0.3-40-gedee635 doesn't seem to notice when the IRC connection drops, and then it doesn't seem to be able to reconnect without being restarted.

I couldn't see any logs anywhere, so can't really add anything useful :(

**Comment by ShaneMcC** [comment]
«23:34:15» <Dataforce> hmm, if mbassador has a publishAsync method, why is publish() not synchronous?
«23:34:25» <Greboid> lol
«23:34:27» <Greboid> It is!
«23:35:33» <Dataforce> So then why is my state vanishing before my socketClosed handler gets the message that the socket is closed, despite resetState() coming after the socketclosed publish() ?
«23:35:55» <MD87> Is this within the parser?
«23:36:26» <MD87> Also I think handlers can be declared as asynchronous
«23:36:30» * MD87 goes back to RL
«23:37:13» <Dataforce> (fyi, disable server side logging and it in theory will fix the disconnect problem)
«23:39:04» <Dataforce> What appears to be happening, is that the socketclosed handler for the logging is trying to close all the log files (part of which includes writing a message to the logs from the client) then it's trying to getImportantModePrefix from the parser for a channelclient and the parser having no modes
«23:39:11» <Greboid> WHY AYE MAN!
«23:39:17» <Dataforce> because it has resetState() following the close
«23:40:04» <Dataforce> At least that's my current working theory.
«23:43:19» <Greboid> That is a sensible working theory
«23:48:00» <Dataforce> oh, I Think it might be even more icky.
«23:49:49» <Greboid> NOSE ICKY!
«23:51:23» <Dataforce> It's detecting the ping timeout, so calling disconnect() which closes the socket and fires callSocketClose()/resetState() (in order). callSocketClose() IS behaving sync, but while that is happening the normal parser timer detects that the socket is closed and goes again - this time notcing that the internal state for the parser is socketState = CLOSED, skipsover the callSocketClosed() call straight to resetState()
«23:51:32» «Important»<Greboid> Icky Shane code, or Icky eventbousing
«23:51:50» <Greboid> lol
«23:51:54» <Dataforce> but at the same time, the original socketClosed events from call from the pingTimer Thread are still trying to access parser state.
«23:52:08» <Greboid> That sounds fun
«23:52:15» <Dataforce> which has just been reset from a different thread
«23:52:41» <Dataforce> and then there is an exception in the DFBNC ServerLogger trying to access modes which have now been reset out of existance.
«23:52:47» <Dataforce> which stops the dfbnc reconnecttimer working.

**Comment by ShaneMcC** [comment]
Blocked on https://github.com/DMDirc/Parser/pull/102

**Comment by csmith** [comment]
Fixed, @ShaneMcC just mucked up the auto close syntax :)
